### ISSUE TITLE
How do you stop it from closing whatever you're running?

### ISSUE THREAD

**Issue by yuvallanger** [dennwc/inkview#1]

**Comment by dennwc** [comment]
Sorry, but I'm not quite sure what is your question. Can you please elaborate?

**Comment by yuvallanger** [comment]
Thank you for replying!

I am writing a small program which allows one to type in shell commands into a web form on the PocketBook device and receive its output. A sort of primitive terminal.

https://gitgud.io/yuvallanger/webpbterm/

I have tried running it by pressing the icon representing my executable, whose path is `/mnt/ext1/applications/webpbterm.app`, but it vanishes a moment later, even though I would expect the program to stay in the background, showing in the Task list, with port :9600 open for user commands.

I was hoping to find out how the SDK stops the PocketBook system from closing down its processes.

I have also opened a stackoverflow question here:

https://stackoverflow.com/questions/52563313/how-do-you-stop-the-pocketbook-system-from-closing-your-program
